name: Publish to GitHub Packages

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Build and Publish to GitHub Packages
        run: ./gradlew publish
        env:
          USERNAME: ${{ secrets.USERNAME }} 
          GITHUB_TOKEN:  ${{ secrets.GH_PACKAGES_TOKEN }}
          
      - name: Display Dependency Tree
        run: ./gradlew dependencies --configuration compileClasspath
        env:
          USERNAME: ${{ secrets.USERNAME }}
          GITHUB_TOKEN: ${{ secrets.GH_PACKAGES_TOKEN }}    

      - name: upload artifact
        uses: actions/upload-artifact@v4.4.3
        with:
          # Artifact name
          name: test-biblioteca
          # A file, directory or wildcard pattern that describes what to upload
          path: /*
