name: Publish to GitHub Packages

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Build and Publish to GitHub Packages
        run: ./gradlew publish
        env:
          USERNAME: WillClever 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
